name: Setup code checks
description: "Setup toolchain and run smoke test"
runs:
  using: composite
  steps:
    - name: ⬇️ Install uv
      uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7
    - name: ⬇️  Setup Python
      run: uv python install
      shell: bash
    - name: ⬇️ Build python package
      run: make package
      shell: bash

