name: Setup code checks
description: "Setup toolchain and run smoke test"
runs:
  using: composite
  steps:
    - name: ⬇️ Install uv
      uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6
    - name: ⬇️  Setup Python
      run: uv python install
      shell: bash
    - name: ⬇️ Build python package
      run: make package
      shell: bash

