name: Code check On outscale

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  code-check:
    runs-on: ubuntu-24.04
    environment: eu-west-2
    if: "! contains(github.event.pull_request.labels.*.name, 'dependencies')"
    steps:
    - name: 🧹 Frieza
      uses: outscale/frieza-github-actions/frieza-clean@68ffd39d7e181f3548369e332242b329b04a3182 # master
      with:
        access_key: ${{ secrets.OSC_ACCESS_KEY }}
        secret_key: ${{ secrets.OSC_SECRET_KEY }}
        region: ${{ secrets.OSC_REGION }}
    - name: ⬇️ Checkout repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
    - name: Setup toolchain
      uses: ./.github/actions/setup-test
    - name: 🧪 Run integration tests
      env:
        OSC_ACCESS_KEY: ${{ secrets.OSC_ACCESS_KEY }}
        OSC_SECRET_KEY: ${{ secrets.OSC_SECRET_KEY }}
        OSC_TEST_LOGIN: ${{ secrets.OSC_TEST_LOGIN }}
        OSC_TEST_PASSWORD: ${{ secrets.OSC_TEST_PASSWORD }}
      run: make test-int
