name: Code check On outscale

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  code-check:
    runs-on: [authenticated, Linux]
    if: "! contains(github.event.pull_request.labels.*.name, 'dependencies')"
    steps:
      - name: 🔒🧹 Setup Vault & Frieza
        id: secrets
        uses: outscale/.github/vault-frieza-clean@eb7bd1e0360703d0ad355bce46029ae8d49bac04
        with:
          vault_role: outscale-osc-sdk-python
          osc_account: elm

      - name: ⬇️ Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup toolchain
        uses: ./.github/actions/setup-test
      
      - name: 🧪 Run integration tests
        env:
          OSC_ACCESS_KEY: ${{ steps.secrets.outputs.access_key }}
          OSC_SECRET_KEY: ${{ steps.secrets.outputs.secret_key }}
          OSC_REGION: ${{ steps.secrets.outputs.region }}
        run: make test-int
