name: osc-sdk-python pip publishing

on:
  release:
    types: [released]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-24.04
    environment: publish
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Setup toolchain
      uses: ./.github/actions/setup-test
    - name: Build & Push packages
      run: make upload-package
