name: osc-sdk-python pip publishing

on:
  release:
    types: [released]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-24.04
    environment: publish
    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
    - name: Setup toolchain
      uses: ./.github/actions/setup-test
    - name: Build & Push packages
      run: make upload-package
