name: osc-sdk-python pip publishing

on:
  release:
    types: [released]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-24.04
    environment: publish
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
    - name: Setup toolchain
      uses: ./.github/actions/setup-test
    - name: Build & Push packages
      run: make upload-package
